In [2]:
import numpy as np

# Numpy


*   Numpy array is a **grid of values**, **same type**, index by a **tuple of nonnegative integers**
*   Only supports numeric data types np.int8, np.int32, np.float32, np.half(float 16), etc..<br>
* Number of dimensions is **rank** of array.
  - array of 2x3x4 has **rank 3**
* Shape of an array is a **tuple of integers** giving the **size** of the array along each dimension

## Caution!
* Python arrays and Numpy arrays are different objects!
  - type only works with Python arrays, *shape* for numpy

In [8]:
a = np.array([[1, 2, 3], [2, 3, 4]])
print(type(a), a.shape, a[0][0])
print(a)

<class 'numpy.ndarray'> (2, 3) 1
[[1 2 3]
 [2 3 4]]


In [9]:
# Shape is your hammer. Good tool to debug np array
print(a.shape)

(2, 3)


In [10]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [3]:
b = np.ones((1,2,5,6,7))
print(b.shape)

(1, 2, 5, 6, 7)


In [4]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [5]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
e = np.random.random((2,2)) * 100 # create an array filled with random values
print(e)

[[55.79767934 17.32041205]
 [96.71761295 88.50905637]]


# Arrays
* Slicing: similar to python lists, numpy arrays can be sliced
* since arrays may be multidimensional, you must specify a slice for each dimension of the array
* Example matrix of **shape** (3,4) (rows by 4 columns) and **rank 2**<br>

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A **slice of an array is a view into the same data**, so modifying it will modify the original array

In [12]:
b[0,0] = 77
print(a)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# How can we make a copy(not reference) of an array
c = np.copy(a)
c[0,0] = 100
print(c) # c has the changes but a does not
print(a)

[[100  77   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
