In [2]:
import numpy as np
import pandas as pd

generator = np.random.default_rng(123)
generator

Generator(PCG64) at 0x7921C0D5E180

In [19]:
# Q1
nancy_start_weight = float(input("Enter your weight nancy\n"))
nancy_weights = np.arange(start=nancy_start_weight, stop=90, step=-2.34)
# type should be numpy.ndarray
print(type(nancy_weights))
print(nancy_weights)


Enter your weight nancy
180
<class 'numpy.ndarray'>
[180.   177.66 175.32 172.98 170.64 168.3  165.96 163.62 161.28 158.94
 156.6  154.26 151.92 149.58 147.24 144.9  142.56 140.22 137.88 135.54
 133.2  130.86 128.52 126.18 123.84 121.5  119.16 116.82 114.48 112.14
 109.8  107.46 105.12 102.78 100.44]


In [44]:
# Q2
plots_of_gold = generator.integers(low=2, high=20, size=(7,7))
print(plots_of_gold)
locations = generator.integers(low=0, high=6, size=(5,2))
print(plots_of_gold[locations[:, 0], locations[:, 1]])

[[15 16  4 11  6  6  4]
 [10 19 13  2  6  7  5]
 [ 5 19 13  5 11  8  7]
 [ 9 18 17 11  7 17  5]
 [ 2  4 11 15  6 12  7]
 [ 3 13 10  8 19 19 18]
 [ 5 12  9  6 11 12 16]]
[11  3 16 19  5]


In [48]:
# Q3
ratings = generator.random(size=(10,2))
print(ratings)
ratings[[1,2,7,9], [0,0,0,0]] = np.nan
x = np.where(np.isnan(ratings[:, 0]), ratings[:, 1], ratings[:, 0])
print(x)

result = np.insert(arr=ratings, values=x, axis=1, obj=1)

[[0.50270794 0.85702214]
 [0.91597162 0.08657005]
 [0.4290827  0.29453693]
 [0.78784907 0.3458479 ]
 [0.4851056  0.70657673]
 [0.63521927 0.74343594]
 [0.43092017 0.54132317]
 [0.27214407 0.77709508]
 [0.86629005 0.30212949]
 [0.49775748 0.10460545]]
[0.50270794 0.08657005 0.29453693 0.78784907 0.4851056  0.63521927
 0.43092017 0.77709508 0.86629005 0.10460545]


In [64]:
# Q5
bees = pd.Series([True, True, False, np.nan, np.nan, False, True, np.nan])
knees = pd.Series(np.random.randint(low=0, high=10, size=8))
knees.loc[pd.isna(bees).to_numpy()] *= 2
print(knees)

0     6
1     9
2     4
3     6
4     4
5     0
6     3
7    14
dtype: int64
