# Python assignment
- Taken from and followed Deep Learning Chapter 2 by Chollet

In [1]:
# import the mnist dataset
from tensorflow.keras.datasets import mnist

In [7]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

## Looking at the training data

In [8]:
print(train_images.shape)
print(len(train_labels))
print(train_labels)

(60000, 28, 28)
60000
[5 0 4 ... 5 6 8]


## Looking at the test data

In [10]:
print(test_images.shape)
print(len(test_labels))
print(test_labels)

(10000, 28, 28)
10000
[7 2 1 ... 4 5 6]


## Import keras and layers from keras

In [11]:
from tensorflow import keras
from tensorflow.keras import layers

## define the layers of the model

In [12]:
model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(10, activation='softmax')
])

## Compilation step

In [13]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

## Preparing the image data

In [14]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [15]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.8695 - loss: 0.4647
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 12ms/step - accuracy: 0.9658 - loss: 0.1151
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - accuracy: 0.9795 - loss: 0.0715
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.9847 - loss: 0.0513
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9908 - loss: 0.0353


## Using model to make predictions

In [16]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([6.3196671e-07, 3.5087417e-08, 9.0755078e-05, 9.4655948e-04,
       9.7910613e-09, 1.0554588e-07, 4.1554518e-10, 9.9892408e-01,
       8.8946808e-06, 2.8832401e-05], dtype=float32)

In [18]:
print(predictions[0].argmax())
print(predictions[0][7])

7
0.9989241


In [19]:
test_labels[0]

7

## Evaluate model on new data

In [20]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9726 - loss: 0.0787
test_acc: 0.9767000079154968
