In [5]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam

In [6]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Inputs: x, y
y = np.array([[1], [0], [0], [1]]) # Class(XNOR)

In [7]:
X.shape

(4, 2)

In [10]:
model = Sequential([
    Input(shape=(X.shape[-1],)),
    Dense(2, activation="sigmoid"),
    Dense(1, activation="sigmoid")
])

model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.1), metrics=['accuracy'])
model.fit(X, y, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.7548
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7140
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.6951
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6952
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7036
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7093
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6968
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6912
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.2500 - loss: 0.6883
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0

KeyboardInterrupt: 

In [11]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 29 (120.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20 (84.00 B)

In [12]:
model.get_weights()

[array([[ 6.2687874, 10.028069 ],
        [ 6.2685485, 10.29563  ]], dtype=float32),
 array([-9.52885  , -4.8651485], dtype=float32),
 array([[ 11.201054],
        [-10.219647]], dtype=float32),
 array([4.6833243], dtype=float32)]

## Print weights and bias of model

In [13]:
weights = model.get_weights()
layer = 1
for i in range(0, len(weights), 2):
    print(f'Weights in {layer} layer: {weights[i]}\n')
    print(f'Bias in {layer} layer: {weights[i+1]}\n')
    layer += 1

Weights in 1 layer: [[ 6.2687874 10.028069 ]
 [ 6.2685485 10.29563  ]]

Bias in 1 layer: [-9.52885   -4.8651485]

Weights in 2 layer: [[ 11.201054]
 [-10.219647]]

Bias in 2 layer: [4.6833243]



## predictions

In [14]:
prediction = model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step


In [15]:
prediction

array([[0.99010664],
       [0.00619515],
       [0.00628003],
       [0.9941636 ]], dtype=float32)